### PR TITLE
Features/move esp32 settings to config (#1)

### PR DESCRIPTION
**Pull request by anabolyc**
[ESP32]
I moved key cspot settings into the config, so it can be configured using `menuconfig`, instead of editing `main.cpp` file. Added description into Readme accordingly.

Also added optional status LED (standard GPIO or adressable LED), it is disabled by default, can be enabled and configured again using `menuconfig`. I'm planing to use it as a 'smart speaker', so I think it is nice to have some feedback in case you don't have serial console attached.

### CODE REVIEW

**Comment by HeikoGr** [comment]
this is a great improvement!

**Comment by HeikoGr** [comment]
@anabolyc do you mind to tell us where you are from, so we could enter your wifi?
In other words: you should change your wifi credentials, if the screenshots are not for example only :-D

**Comment by HeikoGr** [comment]
another feedback: @anabolyc can you add decent default values, so the automatic build wouldn't fail?
you can see the build failing here: https://github.com/HeikoGr/cspot/actions/runs/1793708813

**Comment by anabolyc** [comment]
Hi @HeikoGr, good point, fixed both notes above. 
Strangely, I cannot run pipelines in my fork, that's why build error slipped through my attention

**Comment by HeikoGr** [comment]
thank you!
i think you know, that you need to activate workflows before you can use them. so it keeps strange

**Comment by HeikoGr** [comment]
i found a way to add a button:
`on: [push, pull_request, workflow_dispatch]`

**Comment by anabolyc** [comment]
Thanks, [merged](https://github.com/anabolyc/esp32-cspot/commit/96b30a7725339749f87ada990c3818396d60375d)

**Comment by anabolyc** [comment]
Hi @HeikoGr, 

Would you be able to merge it?

**Comment by feelfreelinux** [comment]
Thanks, merged! Btw, if you are working on a smart speaker system - please take a look at github.com/feelfreelinux/euphonium . I think you'd like it :)

**Comment by anabolyc** [comment]
> Thanks, merged! Btw, if you are working on a smart speaker system - please take a look at github.com/feelfreelinux/euphonium . I think you'd like it :)

Yes, i did checked that and it sounds really promising. But given the current state of docs I had really hard time to run it :)

**Comment by feelfreelinux** [comment]
> > Thanks, merged! Btw, if you are working on a smart speaker system - please take a look at github.com/feelfreelinux/euphonium . I think you'd like it :)
> 
> Yes, i did checked that and it sounds really promising. But given the current state of docs I had really hard time to run it :)

Feel free to reach out to me on telegram / discord / mail, I'll guide you through install and improve the docs :)

**Comment by anabolyc** [comment]
> > > Thanks, merged! Btw, if you are working on a smart speaker system - please take a look at github.com/feelfreelinux/euphonium . I think you'd like it :)
> > 
> > 
> > Yes, i did checked that and it sounds really promising. But given the current state of docs I had really hard time to run it :)
> 
> Feel free to reach out to me on telegram / discord / mail, I'll guide you through install and improve the docs :)

I'm actually starting Crowd Supply for [my smart speaker board](https://www.crowdsupply.com/sonocotta/esp32-audio-development-board), you may subscribe if you're interested. As far as I can tell, you're also located in Poland, so I may offer you a free sample if you're planning to develop for esp32 audio furthermore.

**Comment by feelfreelinux** [comment]
> > > > Thanks, merged! Btw, if you are working on a smart speaker system - please take a look at github.com/feelfreelinux/euphonium . I think you'd like it :)
> > > 
> > > 
> > > Yes, i did checked that and it sounds really promising. But given the current state of docs I had really hard time to run it :)
> > 
> > 
> > Feel free to reach out to me on telegram / discord / mail, I'll guide you through install and improve the docs :)
> 
> I'm actually starting Crowd Supply for [my smart speaker board](https://www.crowdsupply.com/sonocotta/esp32-audio-development-board), you may subscribe if you're interested. As far as I can tell, you're also located in Poland, so I may offer you a free sample if you're planning to develop for esp32 audio furthermore.

Great, i'd love to provide some feedback! I'l also working currently on hardware more tailored towards euphonium as a platform, so i'd love to see your take on it :)

**Pull request merged**
