### PR TITLE
Internal DAC and Config files

### PR DESCRIPTION
**Pull request by michal4132**
-Support for config files
-Internal DAC sink
-small fixes
-loading state fix

### CODE REVIEW

**Comment by feelfreelinux** [comment]
Hi! Sorry it took me so long to review this. Everything LGTM, except for littlefs addition. the internal esp32 target is supposed to be a simple example of implementation, instead of fully-featured player. That's why I don't think it's a good idea to have littlefs there.

**Comment by michal4132** [comment]
What about SPIFFS? It's esp-idf component so we won't be adding anything new. I can easly swap this libraries.

**Comment by feelfreelinux** [comment]
> What about SPIFFS? It's esp-idf component so we won't be adding anything new. I can easly swap this libraries.

It doesn't really increase the example's complexity, so it should be fine with spiffs. Thanks a lot :)

**Comment by feelfreelinux** [comment]
Thanks a lot! I'm going to check it out on a real device asap :)

**Pull request merged**
